
source 'http://rubygems.org'
gem 'rake', '~>10.4.2'

# testing
gem 'minitest', '~>5.5.1'
# gem install rspec

# etc
gem 'activerecord', '~>4.2.0'
gem 'nokogiri', '~>1.6.5'
gem 'rubyzip', '~>1.1.6'
gem 'rufus-mnemo', '~>1.2.3'
gem 'sqlite3', '~>1.3.10'
gem 'uuid', '~>2.3.7'
# gem install WikiCreole

# commander
gem 'ansi', '~>1.4.3'
gem 'commander', '~>4.2.1'
gem 'win32console', '~>1.3.2'

# debugging
gem 'byebug', '~>3.0'
# gem 'pry'
# gem 'pry-debugger' # need to be built with DevKit
