
source 'http://rubygems.org'
gem 'rake', '~>10.4.2'

# testing
gem 'minitest', '~>5.7.0'
# gem install rspec

# etc
gem 'activerecord', '~>4.2.3'
gem 'nokogiri', '~>1.6.5'
gem 'rubyzip', '~>1.1.6'
gem 'rufus-mnemo', '~>1.2.3'
gem 'sqlite3', '~>1.3.10'
gem 'uuid', '~>2.3.8'
gem 'mercenary', '~>0.3.5'
gem 'json', '~>1.8.3'
# gem install WikiCreole

# commander
gem 'ansi', '~>1.5.0'
gem 'commander', '~>4.3.4'
gem 'win32console', '~>1.3.2'

# debugging
gem 'byebug', '~>5.0.0'
# gem 'pry'
# gem 'pry-debugger' # need to be built with DevKit
